version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    expose:
      - "8000"
    restart: always
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env 
  nginx:
    image: nginx:1.19.5-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./foodgram.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/code/static/
      - media_volume:/code/media/
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
