# Generated by Django 3.1 on 2020-12-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20201228_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='дополнительный класс'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
