# Generated by Django 3.1 on 2021-01-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20201231_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=20, verbose_name='цвет чекбокса'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=20),
        ),
    ]
